import { ContentItem } from './types';

export const ALL_CONTENT: ContentItem[] = [
  {
    id: 1,
    title: 'Starlight Odyssey',
    description: 'A team of astronauts embarks on a perilous journey to a distant galaxy to find a new home for humanity, but they uncover a secret that could change the course of history.',
    posterUrl: 'https://picsum.photos/seed/p1/400/600',
    backdropUrl: 'https://picsum.photos/seed/b1/1280/720',
    rating: 'PG-13',
    year: 2023,
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    videoId: 'dQw4w9WgXcQ',
    communityRating: 4.5,
    ratingCount: 120543,
  },
  {
    id: 2,
    title: 'Echoes of the Past',
    description: 'A historian discovers a hidden diary that reveals a centuries-old conspiracy. As she delves deeper, she finds herself hunted by a shadowy organization.',
    posterUrl: 'https://picsum.photos/seed/p2/400/600',
    backdropUrl: 'https://picsum.photos/seed/b2/1280/720',
    rating: 'R',
    year: 2022,
    genres: ['Thriller', 'Mystery'],
    videoId: 'y_gD8sgWc-c',
    communityRating: 4.2,
    ratingCount: 89765,
  },
  {
    id: 3,
    title: 'The Last Stand',
    description: 'In a post-apocalyptic world, a small group of survivors must defend their stronghold against a horde of mutated creatures.',
    posterUrl: 'https://picsum.photos/seed/p3/400/600',
    backdropUrl: 'https://picsum.photos/seed/b3/1280/720',
    rating: 'R',
    year: 2024,
    genres: ['Action', 'Horror', 'Sci-Fi'],
    videoId: 'L056hZaO_fc',
    communityRating: 4.8,
    ratingCount: 210987,
  },
  {
    id: 4,
    title: 'City of Neon',
    description: 'A disillusioned detective navigates the rain-slicked streets of a futuristic city, chasing a phantom killer who leaves no trace.',
    posterUrl: 'https://picsum.photos/seed/p4/400/600',
    backdropUrl: 'https://picsum.photos/seed/b4/1280/720',
    rating: 'R',
    year: 2023,
    genres: ['Cyberpunk', 'Noir', 'Thriller'],
    videoId: '2b93p3c_3S4',
    communityRating: 4.6,
    ratingCount: 95432,
  },
  {
    id: 5,
    title: 'Whispers in the Woods',
    description: 'A family\'s camping trip turns into a nightmare when they encounter a malevolent spirit haunting the ancient forest.',
    posterUrl: 'https://picsum.photos/seed/p5/400/600',
    backdropUrl: 'https://picsum.photos/seed/b5/1280/720',
    rating: 'PG-13',
    year: 2021,
    genres: ['Horror', 'Supernatural'],
    communityRating: 3.9,
    ratingCount: 78123,
  },
  {
    id: 6,
    title: 'Ocean\'s Heart',
    description: 'A young marine biologist discovers a lost underwater civilization while searching for a legendary pearl.',
    posterUrl: 'https://picsum.photos/seed/p6/400/600',
    backdropUrl: 'https://picsum.photos/seed/b6/1280/720',
    rating: 'PG',
    year: 2024,
    genres: ['Adventure', 'Family', 'Fantasy'],
    videoId: 's4gBChg6AII',
    communityRating: 4.4,
    ratingCount: 154321,
  },
  {
    id: 7,
    title: 'Chronos Paradox',
    description: 'A brilliant but reckless physicist accidentally invents a time machine and must fix the chaotic timeline he creates before it unravels reality itself.',
    posterUrl: 'https://picsum.photos/seed/p7/400/600',
    backdropUrl: 'https://picsum.photos/seed/b7/1280/720',
    rating: 'PG-13',
    year: 2023,
    genres: ['Sci-Fi', 'Comedy', 'Action'],
    videoId: '3s2-mnhsV_A',
    communityRating: 4.7,
    ratingCount: 189012,
  },
  {
    id: 8,
    title: 'The Golden Compass',
    description: 'In a parallel universe, a young girl embarks on an epic journey to the far North to rescue her friend and other kidnapped children from a mysterious organization.',
    posterUrl: 'https://picsum.photos/seed/p8/400/600',
    backdropUrl: 'https://picsum.photos/seed/b8/1280/720',
    rating: 'PG-13',
    year: 2007,
    genres: ['Fantasy', 'Adventure'],
    videoId: 'YvUOfs2P3gU',
    communityRating: 4.1,
    ratingCount: 250123,
  },
  {
    id: 9,
    title: 'Serenity Valley',
    description: 'A jaded chef moves to a small town to run a quaint diner, only to find that the town holds a magical secret that could heal his past.',
    posterUrl: 'https://picsum.photos/seed/p9/400/600',
    backdropUrl: 'https://picsum.photos/seed/b9/1280/720',
    rating: 'G',
    year: 2022,
    genres: ['Drama', 'Romance', 'Fantasy'],
    communityRating: 4.3,
    ratingCount: 65432,
  },
  {
    id: 10,
    title: 'Dust Devil',
    description: 'A lone rider in a desolate future must protect a vital data cache from a ruthless gang of marauders across a sun-scorched wasteland.',
    posterUrl: 'https://picsum.photos/seed/p10/400/600',
    backdropUrl: 'https://picsum.photos/seed/b10/1280/720',
    rating: 'R',
    year: 2025,
    genres: ['Action', 'Sci-Fi', 'Western'],
    videoId: '8e2fJf71T-k',
    communityRating: 4.9,
    ratingCount: 301234,
  }
];
